spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: usercreationapi
  datasource:
    driver-class-name: org.h2.Driver
    username: postgres
    password: mysecretpassword
    url: "jdbc:h2:mem:postgres;DB_CLOSE_ON_EXIT=FALSE"
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop


