spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: usercreationapi
  datasource:
    driverClassName: org.h2.Driver
    username: postgres
    password:
    url: "jdbc:h2:mem:usercreationapi"
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    #defer-datasource-initialization: true
    open-in-view: false
    generate_ddl: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop

server:
  servlet:
    context-path: /api/v${api.version}

api:
  version: 1




